'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("vbMP3decoder.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0 0 (table 0)
        '''
        '''7 0 (table 1)
        ''' 131073
        ''' 0
        ''' 131073
        ''' 16
        ''' 131073
        ''' 1
        ''' 17
        '''
        '''17 0 (table 2)
        ''' 131073
        ''' 0
        ''' 262145
        ''' 131073
        ''' 16
        ''' 1
        ''' 131073
        ''' 17
        ''' 262145
        ''' 131073
        ''' 32
        ''' 33
        ''' 131073
        ''' 18
        ''' 131073
        ''' 2
        ''' 34
        '''
        '''17 0 (table 3)
        ''' 262145
        ''' 131073
        ''' 0
        ''' 1
        ''' 131073
        ''' 17
        ''' 131073
        ''' 16
        ''' 262145
        ''' 131073
        ''' 32
        ''' 33
        ''' 131073
        ''' 18
        ''' 131073
        ''' 2
        ''' 34
        '''
        '''0 0 (table 4)
        '''
        '''31 0 (table 5)
        ''' 131073
        ''' 0
        ''' 262145
        ''' 131073
        ''' 16
        ''' 1
        ''' 131073
        ''' 17
        ''' 524289
        ''' 262145
        ''' 131073
        ''' 32
        ''' 2
        ''' 131073
        ''' 33
        ''' 18
        ''' 524289
        ''' 262145
        ''' 131073
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property huffman_table() As String
            Get
                Return ResourceManager.GetString("huffman_table", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0.000000000
        '''-0.000015259
        '''-0.000015259
        '''-0.000015259
        '''-0.000015259
        '''-0.000015259
        '''-0.000015259
        '''-0.000030518
        '''-0.000030518
        '''-0.000030518
        '''-0.000030518
        '''-0.000045776
        '''-0.000045776
        '''-0.000061035
        '''-0.000061035
        '''-0.000076294
        '''-0.000076294
        '''-0.000091553
        '''-0.000106812
        '''-0.000106812
        '''-0.000122070
        '''-0.000137329
        '''-0.000152588
        '''-0.000167847
        '''-0.000198364
        '''-0.000213623
        '''-0.000244141
        '''-0.000259399
        '''-0.000289917
        '''-0.000320435
        '''-0.000366211
        '''-0.000396729
        '''-0.000442505
        '''-0.000473022
        '''-0.000534058
        '''-0.000579834
        '''-0.000625 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property synth_table() As String
            Get
                Return ResourceManager.GetString("synth_table", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
